add tests
antontikhonov/AndroidRepo pull request #11
Opened 2021-05-13 21:46 UTC by antontikhonov

- Произведён рефакторинг функционала напоминания о дне рождения;
- `Schedulers` в функциях, использующих rxJava заменены на абстракции, чтобы в перспективе при тестировании можно было использовать свою реализацию, возвращающую  `Schedulers.trampoline()`

- **_Произведено покрытие кода тестами со следующими спецификациями:_**

  **Сценарий 1:** успешное добавление напоминания
  Текущий год - 1999(не високосный) 9 сентября
  Есть контакт Иван Иванович с датой рождения 8 сентября
  И напоминание для этого контакта отсутствует
  
  Когда пользователь кликает на кнопку напоминания в детальной информации контакта Иван Иванович
  
  Тогда происходит успешное добавление напоминания на 2000 год 8 сентября
  
  **Сценарий 2:** успешное добавление напоминания, ДР еще в текущем году не было
  Текущий год - 1999(не високосный) 7 сентября
  Есть контакт Иван Иванович с датой рождения 8 сентября
  И напоминание для этого контакта отсутствует
  
  Когда пользователь кликает на кнопку напоминания в детальной информации контакта Иван Иванович
  
  Тогда происходит успешное добавление напоминания на 1999 год 8 сентября
  
  **Сценарий 3:** успешное удаление напоминания
  Текущий год - 1999(не високосный)
  Есть контакт Иван Иванович с датой рождения 8 сентября
  И для него включено напоминание на 2000 год 8 сентября
  
  Когда пользователь кликает на кнопку напоминания в детальной информации контакта Иван Иванович
  
  Тогда происходит успешное удаление напоминания
  
  **Сценарий 4:** добавление напоминания для контакта родившегося 29 февраля
  Текущий год - 1999(не високосный), следующий 2000(високосный) 2 марта
  Есть контакт Павел Павлович с датой рождения 29 февраля
  И напоминание для этого контакта отсутствует
  
  Когда пользователь кликает на кнопку напоминания в детальной информации контакта Павел Павлович
  
  Тогда происходит успешное добавление напоминания на 2000 год 29 февраля
  
  **Сценарий 5:** добавление напоминания для контакта родившегося 29 февраля в високосный год
  Текущий год - 2000(високосный) 1 марта
  Есть контакт Павел Павлович с датой рождения 29 февраля
  И напоминание для этого контакта отсутствует
  
  Когда пользователь кликает на кнопку напоминания в детальной информации контакта Павел Павлович
  
  Тогда происходит успешное добавление напоминания на 2004 год 29 февраля.

2021-05-14 07:00 UTC, murrcha commented on presentation/src/main/java/site/antontikhonov/android/presentation/fragments/ContactDetailsFragment.kt
> +            currentContact?.let { con -> viewModel.switchBirthdayNotification(con) }
`con` - непонятно, что значит эта переменная, можно просто it оставить

2021-05-14 07:05 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/BirthdayNotificationModelTest.kt
> +    fun notificationController_whenContactHaveNotNotification_andSetNotificationOnNextYear_shouldGetSuccess() {
camelCase - лучше придерживаться этого стиля

2021-05-14 07:21 UTC, murrcha requested changes
Если тестируем интерактор (модель), то это доменный слой, и тесты должны быть в этом же модуле (domain). Это будут модульные (unit) тесты.
Интеграционные тесты - предполагались тесты для вьюмодели, это слой presentation, тесты для вьюмодели должны быть в том же модуле (presentation).

2021-05-17 13:59 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        val contact = ContactDetailsEntity(
можно создать 1 раз контакт и далее использовать copy() с нужными параметрами для каждого теста
чтобы меньше дублировать

2021-05-17 13:59 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)
этот тест вьюмодели напоминает тест доменный

здесь по идее мы должны подписаться на события интерактора и сравнить полученные результаты
для rx можно использовать TestObserver

2021-05-17 14:00 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +    fun notificationControllerWhenContactHaveNotNotificationAndHaveBirthdayOn29FebruaryAndSetNotificationOnNextLeapYearShouldGetSuccess() {
Слишком длинное название метода

2021-05-17 14:01 UTC, murrcha requested changes
Оставила комментарии

2021-05-17 15:16 UTC, antontikhonov commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)
можно здесь немного подробнее? не совсем понял, что требуется

2021-05-21 18:53 UTC, murrcha requested changes
В этой ветке в модуле domain только папка с тестами сейчас
Не хватает исходников с интеракторами и доменными сущностями

2021-05-21 19:00 UTC, murrcha commented on domain/src/test/java/site/antontikhonov/android/domain/BirthdayNotificationModelTest.kt
> +class ContactDetailsViewModelTest {
ContactDetailsViewModelTest - разве здесь тест вьюмодели?
На уровне бизнес логики мы не можем тестировать вьюмодель, ее мы тестируем на уровне presentation
Здесь же скорее тест модели - ContactDetailsModelTest

2021-05-21 19:01 UTC, murrcha commented on domain/src/test/java/site/antontikhonov/android/domain/BirthdayNotificationModelTest.kt
> +        calendarRepository = CalendarModel()
Здесь странно, что у нас репозиторий инициализируется моделью

2021-05-21 19:10 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)
К примеру, сценарий
Когда пользователь кликает на кнопку напоминания в детальной информации контакта Иван Иванович
Тогда происходит успешное добавление напоминания на 2000 год 8 сентября

На уровне domain мы проверяем интерактор - это уже добавлено
На уровне presentation проверяем вьюмодель - это нужно добавить
То есть, пользователь нажимает кнопку или переключатель
У вьюмодели вызываются соответствующие методы, далее получаем соответствующий результат исходя из заданных условий и проверяем, совпало или нет с ожидаемым

2021-05-22 07:32 UTC, antontikhonov commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)
А разве на данный момент это не так? Ведь мы вызываем метод вьюмодели:
`viewModel.switchBirthdayNotification(contact)`
а затем проверяем, вызывался ли метод `set` соответствующего `AlarmManager` с необходимыми аргументами:
`verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)`

2021-05-22 07:35 UTC, antontikhonov commented on domain/src/test/java/site/antontikhonov/android/domain/BirthdayNotificationModelTest.kt
> +class ContactDetailsViewModelTest {
Если я правильно понял, то здесь скорее даже будет `BirthdayNotificationModelTest`, т.к. в данных тестах мы методы экземпляра `BirthdayNotificationModel` вызываем

2021-05-22 07:37 UTC, antontikhonov commented
> В этой ветке в модуле domain только папка с тестами сейчас
> Не хватает исходников с интеракторами и доменными сущностями
>

2021-05-22 07:47 UTC, antontikhonov commented
_В этой ветке в модуле domain только папка с тестами сейчас_
_Не хватает исходников с интеракторами и доменными сущностями_

Странно, у меня все интеракторы и модели отображаются
![image](https://user-images.githubusercontent.com/57672164/119218624-68522d00-baf2-11eb-833b-1d5c503f8048.png)

2021-05-24 07:25 UTC, murrcha commented on presentation/src/test/java/site/antontikhonov/android/presentation/ContactDetailsViewModelTest.kt
> +        verify(alarmManager).set(AlarmManager.RTC_WAKEUP, nextBirthday.timeInMillis, pendingIntent)
На момент проверки тестов на вьюмодель не было

2021-05-24 07:31 UTC, murrcha approved these changes
Принято

2021-05-24 13:15 UTC, merged