add bound service
antontikhonov/AndroidRepo pull request #3
Opened 2021-03-13 10:41 UTC by antontikhonov

1. Необходимо написать привязанный сервис, который будет иметь публичное API предоставляющее список контактов.
2. Список контактов пока захардкодить в константу.
3. Сервис должен предоставлять список контактов на другом потоке программы.

Сценарий использования:
- Главная активность привязывается к сервису с помощью bindService;
- Получает публичный интерфейс сервиса;
- Предоставляет публичный интерфейс сервиса фрагментам;
- Фрагменты используют публичный интерфейс сервиса для получения данных контактов.

Публичный интерфейс должен иметь 2 метода:
1. Асинхронный метод получения списка контактов с короткой информацией.
2. Асинхронный метод получения детальной информации по ID контакта.

2021-03-14 16:08 UTC, murrcha requested changes
Отлично!
Есть минорные замечания

2021-03-14 16:08 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +    private var contactService: ContactService? = null
При уничтожении активности нужно обнулить ссылку на сервис

2021-03-14 16:50 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +    fun loadContactById() = serviceInterface?.getService()?.getContactById(callback, contactId!!)
дело в том, что из Bundle приходит Nullable значение, значит стоит сделать так?
`contactId = arguments?.getInt(EXTRA_CONTACT_ID)!!
`

2021-03-14 16:50 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        loadContactById()
да, думаю стоит поместить получение данных в onViewCreated на данном этапе, а если будут диалоговые окна, например с редактированием данных контакта, тогда нужно будет поместить в onResume, если я правильно понимаю

2021-03-15 05:21 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +    fun loadContactById() = serviceInterface?.getService()?.getContactById(callback, contactId!!)
!! - небезопасное извлечение nullable переменной, на проектах его не используем.
? - безопасное извлечение nullable переменной - используем.
Можно предоставить значение по умолчанию, если у нас первое выражение вернуло null
`val contactId: Int = arguments?.getInt(EXTRA_CONTACT_ID) ?: -1`
В данном случае contact id является обязательным аргументом для данного экрана, поэтому вместо значения по умолчанию лучше вернуть ошибку
`val contactId: Int = arguments?.getInt(EXTRA_CONTACT_ID) ?: throw IllegalArgumentException("Contact ID required")`

2021-03-15 05:22 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        loadContactById()
Даже если будет диалоговое окно, то вью при этом останется на месте

2021-03-15 05:23 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +                val phoneNum2TextView = view!!.findViewById<TextView>(R.id.contactNum2)
Используем только безопасное извлечение

2021-03-15 05:26 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        loadContactById()
После вызова onStart, экран уже виден пользователю, а мы только здесь загружаем данные, поэтому и возник вопрос, почему здесь, а не раньше

2021-03-15 05:29 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +            contactService = null
Здесь лучше вынести из условия, так как мы можем потерять привязку, а ссылка останется

2021-03-15 06:00 UTC, murrcha approved these changes
Принято

2021-03-15 06:17 UTC, merged