add contact's birthday notification
antontikhonov/AndroidRepo pull request #4
Opened 2021-03-19 11:54 UTC by antontikhonov

1. Необходимо добавить к деталям контакта поле "День рождения" в формате "число месяц"
2. Кнопку которая будет иметь 2 состояния - "Включить напоминания" и "Выключить напоминания"
3. Состояние кнопки должно зависеть от того, добавлена ли уже задача в AlarmManager или нет.
4. При нажатии кнопки в состоянии "Включить напоминания" - должна ставиться задача на вызов вашего BroadcastReceiver'а на число в поле "День рождения" в качестве данных в Intent должен передаваться ID выбранного контакта и текст напоминания "Сегодня день рождения у $s", где $s - имя контакта
5. При нажатии кнопки в состоянии "Выключить напоминания" - должна производиться отмена предстоящей задачи в AlarmManager и состояние кнопки должно обновиться на "Включить напоминания"
6. При нажатии пользователем на уведомление - должна запуститься активность вашего приложения, при этом должен сразу открыться экран с деталями контакта у которого день рождение, уведомление при этом должно исчезнуть из шторки уведомлений.

2021-03-19 18:12 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +            isNotificationsEnabled = true
`isNotificationsEnabled = PendingIntent.getBroadcast(context, contactId, Intent(activity, MyReceiver::class.java), PendingIntent.FLAG_NO_CREATE) != null`
можно упростить

2021-03-19 18:16 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +            val pendingIntent = createPendingIntent()
чтобы метод onViewCreated не разрастался, логику по нажатию на кнопку лучше вынести в отдельный метод

2021-03-19 18:22 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        val monthBirthday: String = currentContact.birthday?.split(" ")?.get(1) ?: throw IllegalArgumentException("Month birthday required")
Еще можно воспользоваться функцией requireNotNull для обязательного параметра
`val value = requireNotNull(currentContact.birthday?.split(" ")?.get(0)?.toInt())`

2021-03-19 18:30 UTC, murrcha commented on app/src/main/res/values/strings.xml
> +    <string name="january">января</string>
можно использовать массив
https://developer.android.com/guide/topics/resources/string-resource#StringArray

2021-03-19 18:34 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/Model.kt
> +                   val birthday: String?,
Не самый удобный формат для хранения, можно хранить отдельно число и месяц в Int, например, будет проще, если не хочется оборачивать это отдельно в какой-то объект

2021-03-19 18:38 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras?.getInt(EXTRA_CONTACT_ID) != null) {
Если нажать назад на детальном экране, который открылся по уведомлению, мы попадем назад на список?

2021-03-20 16:35 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras?.getInt(EXTRA_CONTACT_ID) != null) {
Действительно, этот момент не учёл сразу, теперь попадём

2021-03-21 14:54 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras?.getInt(EXTRA_CONTACT_ID) != null && savedInstanceState == null) {
При запуске по иконке открывается сразу детальный экран

2021-03-21 15:04 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras?.getInt(EXTRA_CONTACT_ID) != null && savedInstanceState == null) {
`intent.extras?.getInt(EXTRA_CONTACT_ID) != null` - всегда **true**
Поэтому всегда будем при старте приложения попадать на детальный экран
Почему так происходит, можно посмотреть реализацию метода `getInt`

2021-03-21 15:05 UTC, murrcha requested changes
Есть замечание по навигации при старте приложения по иконке

2021-03-21 15:55 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras != null && savedInstanceState == null) {
если у нас будут любые другие extras, то мы всегда будем попадать на детальный
возможно стоит рассмотреть проверку на дефолтное значение?

2021-03-21 16:39 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras != null && savedInstanceState == null) {
`if(intent.extras?.containsKey(EXTRA_CONTACT_ID) == true && savedInstanceState == null)`
Могу ли я использовать такое условие? И ещё такое замечание, на данный момент у меня на двух эмуляторах и смартфоне загружается именно список, это связано с тем, что intent.extras == null при первом запуске и повороте, поэтому условие не выполняется. Насколько я понимаю, проверку нужно изменить на тот случай, если в дальнейшем захотим переопределить getOnSaveInstanceState()?

2021-03-21 17:14 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        if(intent.extras != null && savedInstanceState == null) {
`if(intent.extras?.containsKey(EXTRA_CONTACT_ID) == true` - да, так тоже можно
По идее это 2 независимых условия:
1) Если у вас активность создается 1й раз, то добавляем экран со списком. Если пересоздается, то экран со списком уже добавлять не надо.
2) Если у нас есть интент с ид контакта, то меняем экран на детальный.

Можно упростить

2021-03-21 17:26 UTC, murrcha approved these changes
Принято

2021-03-21 21:08 UTC, merged