add contact resolver
antontikhonov/AndroidRepo pull request #5
Opened 2021-03-27 20:44 UTC by antontikhonov

Необходимо реализовать загрузку контактов пользователя из поставщика контактов:
1. В существующем методе загрузки списка контактов - получать список всех контактов пользователя из поставщика контактов
2. В существующем методе загрузки деталей контакта по ID - получать все необходимые данные контакта из поставщика контактов по ID

2021-03-28 10:25 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +    companion object {
`companion object` здесь не нужен, достаточно сделать `object` вместо `class` у `ContactResolver`

2021-03-28 10:28 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            try {
здесь можно использовать `try with resources`, а лучше `use`
https://www.baeldung.com/kotlin/try-with-resources

2021-03-28 10:32 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                        val contact = Contact(id, contactName, contactPhone, null, null, null, null, contactPhotoUri)
При создании Contact лучше использовать именованные параметры, каждый с новой строки (удобнее читается). Например,
```
Contact(
    id = id, 
    name = contactName, 
    phone = contactPhone, 
    other = null, 
    photo = contactPhotoUri
)
```

2021-03-28 10:33 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val uri = Contacts.CONTENT_URI
Это можно вынести в константу, повторяется в нескольких местах

2021-03-28 10:41 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                if(cursor != null) {
Предпочтительно использовать kotlin стиль
```
cursor?.let {
    ...
}
```

2021-03-28 10:42 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val contactEmail: ArrayList<String> = getListEmails(contentResolver, id)
`val contactEmail: List<String>`

2021-03-28 10:43 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        private fun getListPhones(contentResolver: ContentResolver, id: String): ArrayList<String> {
`ArrayList<String>` -> `List<String>`

2021-03-28 10:44 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val listPhoneNumbers: ArrayList<String> = ArrayList()
val listPhoneNumbers = mutableListOf<String>()

2021-03-28 10:47 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val listEmails: ArrayList<String> = ArrayList()
`val listEmails = mutableListOf<String>()`

2021-03-28 10:49 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val selection = Data.CONTACT_ID + " = " + id + " AND " + Data.MIMETYPE + "= '" +
Вынести в константу, здесь и в других местах

2021-03-28 10:53 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                    if(!photoCursor.moveToFirst()) {
Для чего запрашиваем курсор и не используем его потом?

2021-03-28 10:58 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        MaterialAlertDialogBuilder(requireContext())
Необходимо создать зависимый от ЖЦ диалог-фрагмент, наследуемый от DialogFragment и использовать его для отображения диалога

2021-03-28 10:59 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +                    dialog, which ->  requestPermissionLauncher.launch(Manifest.permission.READ_CONTACTS)
`dialog, which` -> `_, _` - неиспользуемые параметры нужно поменять на нижнее подчеркивание

2021-03-28 11:29 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +                    imageView?.setImageURI(photoUri)
Здесь приходит uri картинки, но самой картинки по факту нет, поэтому не подставляется плейсхолдер. Нужно разобраться. Возможно некорректно запрашивается ссылка на фото.

2021-03-28 11:39 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                photoUri = Uri.withAppendedPath(person, Contacts.Photo.CONTENT_DIRECTORY)
Есть подозрение, что uri запрашивается некорректно -> `Contacts.Photo.CONTENT_DIRECTORY`
Нужен URI, а не директория.

2021-03-28 11:39 UTC, murrcha requested changes
Есть замечания

2021-03-29 07:09 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/AlertDialogFragment.kt
> +            .setPositiveButton(R.string.noPermissionsDialogButton) { _, _ -> (activity as MainActivity).restartCheckPermission() }
`(activity as MainActivity).restartCheckPermission() ` - возможен вызов exception при обращении к null, если кастинг будет неуспешный, рекомендуется использовать безопасный кастинг
`(activity as? MainActivity)?.restartCheckPermission() `

2021-03-29 08:36 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val cursor = contentResolver.query(
Можно обойтись без переменной `cursor`

2021-03-29 08:37 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val cursor = contentResolver.query(
`cursor` - можно без этой переменной сразу использовать `use`

2021-03-29 08:38 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                listPhoneNumbers.add(it.getString(it.getColumnIndex(CommonDataKinds.Phone.NUMBER)))
Если `getString` вернет null, то приложение упадет при добавлении null в список

2021-03-29 08:39 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                listEmails.add(it.getString(it.getColumnIndex(CommonDataKinds.Email.DATA)))
Аналогично, возможен крэш, если `getString` вернет null

2021-03-29 08:40 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val selection = "$CONTACTS_ID = ?"
Тоже можно вынести в константу

2021-03-29 08:43 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +                photoUri = Uri.parse(it.getString(it.getColumnIndex(Contacts.Photo.PHOTO_URI)))
Если `getString` вернет null, то `NullPointerException if uriString is null`, всегда лучше проверить в исходниках, что может возвращать тот или иной метод.

2021-03-29 08:44 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            name = getString(getColumnIndex(CONTACTS_DISPLAY_NAME)),
Аналогично, `getString` может вернуть `null`, будет крэш, так как `name` non-nullable

2021-03-29 08:46 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            dayOfBirthday = birthday?.split("-")?.get(2)?.toInt(),
Здесь тоже может быть потенциальная ошибка, мы можем не получить массив из 3х элементов.
Разделитель нужно вынести в константу.

2021-03-29 08:50 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val id = getString(getColumnIndex(CONTACTS_ID))
`getString` может вернуть null

2021-03-29 08:55 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MainActivity.kt
> +        val newFragment = AlertDialogFragment.newInstance(resMessage)
Лучше вынести в переменную на уровень класса, и перед отображением проверять, возможно уже диалог создан или уже отображается, тогда не нужно создавать снова, а если отображается, то не показывать снова, это позволит избежать дублирования диалогов. Плюс учесть жц активности и обнулять диалог в соответствующем коллбеке.

2021-03-29 09:15 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +            shower?.displayAlertDialog(R.string.noPermissionsDialogList)
Если пользователь не дал разрешение после запроса, то нужно проверить показывали ли уже диалог
`shouldShowRequestPermissionRationale`, если нет, то показать диалог, для чего нам это разрешение.
Если пользователь нажал не спрашивать снова, то диалог о том для чего нам разрешение показывать бессмысленно, потому что системного диалога для запроса разрешений больше не будет.
В данном случае лучше показать пользователю что мы не можем получить данные без этих разрешений и предложить включить их в настройках, по соответствующей кнопке.
https://developer.android.com/training/permissions/requesting

2021-03-30 05:50 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val selection = "$CONTACTS_ID = ?"
не совсем понял, о чём идёт речь, ведь `CONTACTS_ID` уже константа, а `"Contacts._ID = ?"` в других местах не используется

2021-03-30 08:55 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val selection = "$CONTACTS_ID = ?"
можно так
`private const val SELECTION = "$CONTACTS_ID = ?"`

2021-03-30 12:10 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        lateinit var contact: Contact
`lateinit var contact: Contact` - в этом методе можем получить исключение, что переменная не инициализирована

2021-03-30 13:02 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +        val birthdayList = getBirthdayDate(contentResolver, id)?.split(DATE_SEPARATOR)
`--03-29` - оказывается можно задать дату без года и тогда у контакта будет такая строка с датой, то есть дата есть, но мы ее указать не сможем, возможно нужна еще какая, то проверка, не добавлять в список пустые строки, например

2021-03-30 14:36 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val selection = Data.CONTACT_ID + " = " + id + " AND " + Data.MIMETYPE + "= '" +
т.е. все переменные для функций `query()` стоит вынести в константы, вне зависимости от того, сколько раз они используются в коде?

2021-03-31 05:39 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            val selection = Data.CONTACT_ID + " = " + id + " AND " + Data.MIMETYPE + "= '" +
да, рекомендуется всегда выносить строки в константы, аналогично это касается и `магических чисел`

2021-03-31 05:43 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +            dayOfBirthday = birthdayList[2].toInt()
`toInt()` - здесь  возможна ошибка, если строка будет не число

2021-03-31 11:31 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +    private const val CONTACTS_DISPLAY_NAME = Contacts.DISPLAY_NAME
Contacts.DISPLAY_NAME - это по сути уже константа и ее выносить не нужно и ниже тоже самое

2021-03-31 11:41 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +    private const val CONTACTS_DISPLAY_NAME = Contacts.DISPLAY_NAME
![image](https://user-images.githubusercontent.com/57672164/113138669-2b2a9680-9237-11eb-9f9f-0d17b4c8cec2.png)
Кажется понял, меня смутил вот этот комментарий. Т.е. например это `"${Data.CONTACT_ID}="` стоит выносить в константу, а это `CommonDataKinds.Email.CONTENT_URI` не стоит?

2021-03-31 12:04 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactResolver.kt
> +    private const val CONTACTS_DISPLAY_NAME = Contacts.DISPLAY_NAME
Да, неправильно написала, то есть нужно выносить по сути только сами запросы, содержащие строки. Те константы, что уже есть, их не нужно выносить еще раз в константы

2021-03-31 12:41 UTC, murrcha approved these changes
Принято

2021-03-31 13:05 UTC, merged