refactoring on MVVM
antontikhonov/AndroidRepo pull request #6
Opened 2021-04-02 13:05 UTC by antontikhonov

Произведён рефакторинг существующего кода с использованием архитектурного паттерна MVVM.

В рамках рефакторинга был удалён существующий сервис загрузки контактов, а вся работа по загрузке контактов из сервиса была вынесена в репозиторий, который используется в ViewModel.

2021-04-03 17:00 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        contactObserver = Observer {
contactObserver  - эту переменную проще инициализировать сразу, для чего это делать в onCreate?

2021-04-03 17:04 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        contactListObserver = Observer {
тоже лучше вынести из onCreate просто в класс

2021-04-03 17:05 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactRepository.kt
> +object ContactRepository : IssueRepository {
IssueRepository - почему такое название?

2021-04-03 17:09 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/IssueRepository.kt
> +interface IssueRepository {
Это точно репозиторий для контактов?

2021-04-03 17:11 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/MyReceiver.kt
> +        createNotificationChannel(context)
Создание канала лучше вынести в другое место (например в активность при ее создании), чтобы канал создавался 1 раз, а не каждый раз при создании уведомления

2021-04-03 17:12 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
>      private lateinit var button: Button
эту вью нужно обнулять в onDestroyView (чтобы избежать утечек), поэтому она должна быть nullable

2021-04-03 17:18 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsViewModel.kt
> +       private var repository: ContactRepository = ContactRepository
Для чего эта переменная?

2021-04-03 17:20 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactRepository.kt
> +            Thread {
То есть мы запрашиваем только если у нас не инициализировано поле?

2021-04-03 17:26 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +    private fun loadContacts() = viewModel?.getContactList(requireContext())?.observe(viewLifecycleOwner, contactListObserver)
слишком длинная строка, обычно придерживаются правила, что строка не более 120 символов

2021-04-03 17:27 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactRepository.kt
> +                contactList.postValue(ContactResolver.getContactsList(context.contentResolver))
Проще передавать просто context и уже сам ContactResolver возьмет из него что нужно

2021-04-03 17:27 UTC, murrcha requested changes
В манифесте остался сервис

2021-04-05 16:27 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactRepository.kt
> +            Thread {
Вопрос не значил, что неправильно, интересует какая логика была заложена, запросить 1 раз и всегда отдавать полученное, или запрашивать каждый раз.

2021-04-05 16:31 UTC, murrcha commented
Желательно располагать методы внутри класса в определенной очередности (для упрощения чтение кода)
1) публичные статические методы
2) приватные статические методы
3) методы жц в порядке их вызова
4) другие override методы
5) публичные методы
6) приватные методы

2021-04-05 16:38 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
>          when {
Желательно весь when вынести в отдельный метод
Почему мы всегда подписываемся в onStart?

2021-04-05 17:06 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactRepository.kt
> +            Thread {
Решил, что лучше будет переделать, ибо данные контактов могут измениться, а т.к. LiveData уже будет проинициализирована, то данные в приложении не поменяются

2021-04-05 17:08 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
>          when {
Для того, чтобы при выходе из настроек, в которые мы зашли после того, как поставили галочку "больше не спрашивать", можно было загрузить данные о контакте

2021-04-06 18:41 UTC, murrcha approved these changes
Принято

2021-04-07 07:48 UTC, merged