add recyclerview for contact list
antontikhonov/AndroidRepo pull request #7
Opened 2021-04-09 21:49 UTC by antontikhonov

1. Добавлен поиск по именам с использование SearchView. Каждый новый ввод символа в SearchView приводит к перезапросу данных списка контактов из репозитория. При пустом вводе выводится весь список контактов.

2. Изменения отслеживаются через DiffUtils. Diff производится на отдельном потоке с использование адаптера - ListAdapter.

3. Разделение элементов списка произведено через реализацию кастомного ItemDecoration.

2021-04-11 06:21 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +       object DiffUtilCallback : DiffUtil.ItemCallback<Contact>() {
Вынести в отдельный файл

2021-04-11 06:21 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +       class ContactViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Вынести в отдельный файл

2021-04-11 06:22 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +              val view = LayoutInflater.from(parent.context).inflate(R.layout.contact_item, parent, false)
Можно обойтись без этой переменной

2021-04-11 06:22 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +              holder.itemView.setOnClickListener {
Нужно вешать листенер в момент создания вьюхолдера

2021-04-11 06:23 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +                            itemClickListener?.onItemClick(getItem(adapterPosition).id)
Вьюхолдер должен передавать позицию адаптеру
Адаптер должен передавать по этой позиции item из списка дальше

2021-04-11 06:23 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +       interface ItemClickListener {
Проще использовать лямбды

2021-04-11 06:25 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +            recyclerView?.addItemDecoration(ContactDecorator(drawableDivider, convertDpToPx(16)))
Декоратор можно инициализировать 1 раз при создании фрамента
Размер нужно вынести в ресурсы

2021-04-11 06:26 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        adapter = ContactListAdapter(itemClickListener)
Адаптер можно инициализировать 1 раз при создании фрамента

2021-04-11 06:28 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +    private fun initializeRecyclerView() {
Размер RecyclerView меняется на экране?

2021-04-11 06:28 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        recyclerView?.adapter = adapter
не обнуляется адаптер у RecyclerView в onDestroyView

2021-04-11 06:29 UTC, murrcha requested changes
Оставила комментарии

2021-04-11 09:49 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +                            itemClickListener?.onItemClick(getItem(adapterPosition).id)
Здесь не совсем понял, ведь по идее мы как раз получаем позицию с помощью `holder.adapterPosition`, а затем получаем элемент через `getItem(adapterPosition)`

2021-04-11 09:51 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +       interface ItemClickListener {
Здесь тоже, вроде если лямбду в `ContactListAdapter` будет передавать `ContactListFragment`, а выполнять смену фрагментов `MainActivity`, то всё равно не получится обойтись без интерфейса

2021-04-11 10:02 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +    private fun initializeRecyclerView() {
recyclerView?.setHasFixedSize(true)

2021-04-11 12:55 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +    private fun initializeRecyclerView() {
да

2021-04-11 13:01 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +                            itemClickListener?.onItemClick(getItem(adapterPosition).id)
Необходимо разделить эти сущности: адаптер и вьюхолдер
Вьюхолдер не знает о внутренней реализации адаптера и не должен
Вью холдер знает только свою позицию
Он ничего не знает о списке с данными
Об этом знает адаптер, это его ответственность отдать айтем по позиции
Ответственность вьюхолдера - передать позицию при клике адаптеру

2021-04-11 13:03 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +       interface ItemClickListener {
Тем не менее можно обойтись без объявления лишнего интерфейса

2021-04-11 13:05 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDecorator.kt
> +                       private val offsetPx: Int) : RecyclerView.ItemDecoration() {
@Px

2021-04-11 13:06 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDecorator.kt
> +class ContactDecorator(private val dividerDrawable: Drawable,
`@DrawableRes private val dividerDrawable: Drawable`

2021-04-11 16:09 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +class ContactListAdapter(private val replaceDetailsFragment: (String) -> Unit?) : ListAdapter<Contact,
Unit? - для чего nullable?

2021-04-11 16:11 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +              holder.itemView.setOnClickListener {
`itemView.setOnClickListener { `- нужно вынести в класс вьюхолдера

2021-04-11 16:24 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDecorator.kt
> +              for(i in 0 until parent.childCount - 1) {
`repeat(parent.childCount)`

2021-04-11 16:35 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        context?.resources?.getDimensionPixelSize(R.dimen.main_padding) ?: 32
32 - непонятное значение, если это размер - то нужно его вынести в ресурсы

2021-04-11 16:36 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        adapter = ContactListAdapter { id: String -> (context as? MainActivity)?.replaceContactDetailsFragment(id) }
id: String - тип можно не указывать

2021-04-11 16:41 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        recyclerView = requireView().findViewById(R.id.recycler_view)
мы же можем передавать в метод инициализации view из onViewCreated, тогда requireView() не нужен

2021-04-11 16:42 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        recyclerView?.setHasFixedSize(true)
Также чтобы не повторять несколько раз recyclerView, можно использовать `with(recyclerView){ ... }`

2021-04-11 16:46 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        context?.resources?.getDimensionPixelSize(R.dimen.main_padding) ?: 32
Разве так не работает `resources.getDimensionPixelSize(R.dimen.main_padding)`?

2021-04-11 20:02 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDecorator.kt
> +              for(i in 0 until parent.childCount - 1) {
`repeat(parent.childCount)` для каждого элемента разделитель нарисует, а по задумке было так, чтобы под последним элементом не было черты

2021-04-11 20:12 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        context?.resources?.getDimensionPixelSize(R.dimen.main_padding) ?: 32
Работает, но тогда `offsetPx` получается nullable и в конструктор приходится помещать через `let`. Это нормальная практика? 
`contactDecorator = offsetPx?.let { ContactDecorator(drawableDivider, it) }`

2021-04-11 20:50 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +              holder.itemView.setOnClickListener {
Теперь ещё меньше понимаю, нужно при создании `ContactViewHolder` настроить listener на itemView, т.е. в блоке `init {}`? Но в этот момент у нас ещё нет конкретного контакта, у которого мы можем позаимствовать id для лямбды.

2021-04-11 21:40 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListAdapter.kt
> +              holder.itemView.setOnClickListener {
Вьюхолдер должен передавать позицию адаптеру, а уже адаптер должен по этой позиции получать элемент и передавать куда нужно. При создании вьюхолдера (в методе  onCreateViewHolder) в его конструктор нужно передать лямбду click:(Int)->Unit. Таким образом, вьюхолдер передаёт позицию адаптеру. А уже в адаптере можно получить по этой позиции элемент. В адаптере это будет примерно так:
ContactViewHolder(view) { position ->
  onContactClick(getItem(position))
}

Соответственно во вьюхолдере: 

init {

  itemView.setOnClickListener {
  val position = adapterPosition
if(position != NO_POSITION) {
onItemClick(position)
}
}

2021-04-12 16:46 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +        context?.resources?.getDimensionPixelSize(R.dimen.main_padding) ?: 32
если вызвать эту строку в onCreate, то размер приходит корректно
`val offsetPx = resources.getDimensionPixelSize(R.dimen.main_padding)`

можно обойтись без конструкции 
```
private val offsetPx by lazy {
        context?.resources?.getDimensionPixelSize(R.dimen.main_padding)
```

2021-04-12 16:49 UTC, murrcha approved these changes
Все хорошо, остался только комментарий по инициализации offsetPx для декоратора списка.
В остальном принято

2021-04-14 20:07 UTC, merged