refactoring on RxJava
antontikhonov/AndroidRepo pull request #8
Opened 2021-04-17 09:51 UTC by antontikhonov

1. Получение данных происходит в io потоке.
2. Отображение данных происходит на главном потоке.
3. Реализована индикация загрузки данных с помощью `ProgressBar` и оператора doOnSubscribe.
4. `Disposable.dispose()` вызывается в `onCleared()` вьюмодели.

2021-04-18 07:58 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsViewModel.kt
> +                                   onError = { it.printStackTrace() }
При ошибке прогресс бар останется висеть?

2021-04-18 08:01 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsViewModel.kt
> +       private val disposable: CompositeDisposable by lazy { CompositeDisposable() }
почему нельзя сразу проинициализировать?

2021-04-18 08:04 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsFragment.kt
> +        viewModel?.isLoading()?.observe(viewLifecycleOwner, Observer { if(it) progressBar?.visibility = View.VISIBLE else progressBar?.visibility = View.GONE })
для if не хватает скобочек, плюс очень длинная строка

2021-04-18 08:10 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListFragment.kt
> +            if(isLoading) progressBar?.visibility = View.VISIBLE else progressBar?.visibility = View.GONE
if {} else {}

2021-04-18 08:11 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +       private val disposable: CompositeDisposable by lazy { CompositeDisposable() }
аналогично

2021-04-18 08:12 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +                            onError = { it.printStackTrace() }
при ошибке прогресс бар останется висеть, плюс ошибку в лог через логгер

2021-04-18 08:13 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +                            onError = { it.printStackTrace() }
Ошибку в лог через логгер, отключать прогресс

2021-04-18 08:19 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +              disposable.add(subject.debounce(300, TimeUnit.MILLISECONDS)
В конце цепочки можно использовать функцию расширения из rxkotlin
`.addTo(disposable)`

2021-04-18 08:21 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +       fun getContactList(context: Context): LiveData<List<Contact>> {
`LiveData<List<Contact>>` данный возвращаемый тип здесь не нужен
по итогу результат все равно в LiveData

2021-04-18 08:22 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +              return contacts
ну нужно, уже есть `contacts.postValue(it)`

2021-04-18 08:25 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactDetailsViewModel.kt
> +       fun getContactById(context: Context, id: String): LiveData<Contact> {
`LiveData<Contact>`  - возвращаемый тип не нужен, уже есть `contact.postValue(it)`

2021-04-18 08:33 UTC, murrcha requested changes
Есть замечания

2021-04-19 08:43 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListViewModel.kt
> +              return contacts
Т.е. класс поля `contacts` должен быть `LiveData`, и во `View` подписываемся на это `public` поле?

2021-04-19 20:16 UTC, merged