refactoring on Dagger 2
antontikhonov/AndroidRepo pull request #9
Opened 2021-04-25 14:49 UTC by antontikhonov

**Произведен рефакторинг с использованием Dagger 2.**

Используются различные Scopes:
`@Singleton` для зависимостей предоставляемых на время жизни всего приложения.
`@ContactsListScope` - для зависимостей, предоставляемых на время жизни экрана списка контактов.
`@ContactsDetailsScope` - для зависимостей, предоставляемых на время жизни экрана с деталями контакта.

Зависимости между компонентами реализованы через subcomponents.

2021-04-25 15:45 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListApplication.kt
>  class ContactListApplication : Application() {
`: DaggerApplication()`

2021-04-25 16:10 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/fragments/ContactDetailsFragment.kt
>  class ContactDetailsFragment : Fragment(R.layout.fragment_contact_details) {
`: DaggerFragment(...)`

2021-04-25 16:11 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/fragments/ContactListFragment.kt
>  class ContactListFragment : Fragment(R.layout.fragment_contact_list) {
`: DaggerFragment(...)`

2021-04-25 16:14 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/fragments/ContactDetailsFragment.kt
> +        ContactListApplication.appComponent.plusContactDetailsComponent().inject(this)
В DaggerFragment уже выполняется иньекция
![image](https://user-images.githubusercontent.com/18559291/116000823-d47c6680-a602-11eb-8e5b-6dc829137342.png)

2021-04-25 16:17 UTC, murrcha commented on app/build.gradle
> +    implementation "com.google.dagger:dagger-android:$dagger_version"
`com.google.dagger:dagger-android-support`

2021-04-25 16:17 UTC, murrcha requested changes
Оставила комментарии

2021-04-25 16:42 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListApplication.kt
>  class ContactListApplication : Application() {
Решено использовать голый даггер, данная зависимость не нужна

2021-04-25 16:42 UTC, murrcha commented on app/build.gradle
> +    implementation "com.google.dagger:dagger-android:$dagger_version"
лишняя зависимость

2021-04-25 16:42 UTC, murrcha commented on app/build.gradle
> +    kapt  "com.google.dagger:dagger-android-processor:$dagger_version"
аналогично

2021-04-25 16:43 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/fragments/ContactDetailsFragment.kt
> +        ContactListApplication.appComponent.plusContactDetailsComponent().inject(this)
до super

2021-04-25 16:44 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/fragments/ContactListFragment.kt
> +        ContactListApplication.appComponent.plusContactListComponent().inject(this)
до super

2021-04-26 19:40 UTC, antontikhonov commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListApplication.kt
> +    companion object {
чтобы во фрагментах не вызывать конструктор класса `ContactListApplication`, или лучше объявить как нестатическую переменную и вызывать `ContactListApplication().appComponent.plusContactDetailsComponent().inject(this)`?

2021-04-27 04:55 UTC, murrcha commented on app/src/main/java/site/antontikhonov/android/lesson1/ContactListApplication.kt
> +    companion object {
вызывать ContactListApplication() не нужно
нужно просто сделать геттер для  нестатичного appComponent и пользоваться им
плюс должна быть проверка на инициализацию, если поле не инициализировано, то инициализировать

2021-04-27 07:21 UTC, murrcha approved these changes
Принято

Как продвигается курсовая?

В задание с курсовой можно оформлять PR с тем что уже готово

2021-04-27 17:12 UTC, antontikhonov commented
изучаю библиотеки, которые понадобятся, код пока не пишу, потому что кажется, что сложно будет после каждой домашки делать merge из main, ведь по clean architecture, наверное, опять сильно структура проекта изменится, или я заблуждаюсь?

2021-04-28 10:13 UTC, murrcha commented
> изучаю библиотеки, которые понадобятся, код пока не пишу, потому что кажется, что сложно будет после каждой домашки делать merge из main, ведь по clean architecture, наверное, опять сильно структура проекта изменится, или я заблуждаюсь?

судя по следующему заданию, будет разбиение на модули
лучше, конечно, если не сделано еще ничего, делать после этого дз
далее останутся тесты и GitFlow
с другой стороны, уже сейчас пробовать что-то в отдельной ветке можно
например, работу с картами, сетевые запросы, работа с бд
из библиотек достаточно будет google maps, retrofit, room

2021-04-28 19:25 UTC, merged